# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a data set which contains information World cup matches. Let's use the pandas commands learned in the previous lecture to learn more about our data!

## Objectives
You will be able to:
* Understand and explain some key Pandas methods
* Access DataFrame data by using the label
* Perform boolean indexing on both Series and DataFrames
* Use simple selectors for series
* Set new Series and DataFrame inputs

## Load the data

Load the file `WorldCupMatches.csv` as a dataframe in Pandas

In [1]:
import pandas as pd
df = pd.read_csv('WorldCupMatches.csv')
len(df)

852

## Common methods and attributes

Use the correct method to look at the first 7 rows of the data set.

In [2]:
df.iloc[0:7]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

Look at the last 3 rows of the data set.

In [3]:
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of your data using `.info()`

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
Year                    852 non-null int64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null int64
Away Team Goals         852 non-null int64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null int64
Half-time Away Goals    852 non-null int64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null int64
MatchID                 852 non-null int64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [13]:
df.shape

(852, 20)

Use the appropriate attribute to get the column names

In [5]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting dataframe information

When looking at the dataframe's `.head()`, you might have noticed that the games are structured chronologically in the dataframe.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [6]:
df.iloc[3:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX

Now, print all the info from game 5-9, but we're only interested to print out the "Home Team Name" and the "Away Team Name",

In [7]:
df.loc[5:10,['Home Team Name','Away Team Name']]

   Home Team Name Away Team Name
5           Chile         Mexico
6      Yugoslavia        Bolivia
7             USA       Paraguay
8         Uruguay           Peru
9           Chile         France
10      Argentina         Mexico

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
Year                    852 non-null int64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null int64
Away Team Goals         852 non-null int64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null int64
Half-time Away Goals    852 non-null int64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null int64
MatchID                 852 non-null int64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

In [9]:
df[(df['Year'] == 1950) & (df['Stage'] == 'Group 1')]
# df[(df['Year'] == 1950)]
# df[(df['Stage'] == 'Group 3')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
53,1950,24 Jun 1950 - 15:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,4,0,Mexico,,81649.0,1,0,READER George (ENG),GRIFFITHS Benjamin (WAL),MITCHELL George (SCO),208,1187,BRA,MEX
57,1950,25 Jun 1950 - 15:00,Group 1,Independencia,Belo Horizonte,Yugoslavia,3,0,Switzerland,,7336.0,0,0,GALEATI Giovanni (ITA),EKLIND Ivan (SWE),DATTILO Generoso (ITA),208,1230,YUG,SUI
58,1950,28 Jun 1950 - 15:00,Group 1,Pacaembu,Sao Paulo,Brazil,2,2,Switzerland,,42032.0,2,1,AZON ROMA Ramon (ESP),BUSTAMANTE Sergio (CHI),DE NICOLA Cayetano (PAR),208,1188,BRA,SUI
59,1950,28 Jun 1950 - 15:00,Group 1,Eucaliptos,Porto Alegre,Yugoslavia,4,1,Mexico,,11078.0,2,0,LEAFE Reginald (ENG),DAHLNER Gunnar (SWE),VAN DER MEER Karel (NED),208,1225,YUG,MEX
63,1950,01 Jul 1950 - 15:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,2,0,Yugoslavia,,142429.0,1,0,GRIFFITHS Benjamin (WAL),BERANEK Alois (AUT),DA COSTA VIEIRA Jose (POR),208,1191,BRA,YUG
67,1950,02 Jul 1950 - 15:40,Group 1,Eucaliptos,Porto Alegre,Switzerland,2,1,Mexico,,3580.0,2,0,EKLIND Ivan (SWE),DAHLNER Gunnar (SWE),BUSTAMANTE Sergio (CHI),208,1222,SUI,MEX

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [13]:
df.loc[(df['Year'] == 1950) & (df['Stage'] == 'Group 3'), ['Attendance']]

    Attendance
56     36502.0
61      7903.0
65     25811.0

Throughout the entire history of the world cup, How many Home games were played by the Netherlands?

In [2]:
len(df.loc[df['Home Team Name'] == 'Netherlands'])

32

How many games were played by the Netherlands in total?

In [3]:
len(df.loc[(df['Home Team Name'] == 'Netherlands') | (df['Away Team Name'] == 'Netherlands')])

54

Next, let's try and figure out how many games the USA played in the 2014 world cup.

In [4]:
len(df.loc[(df['Year'] == 2014) & (df['Home Team Name'] == 'USA') | (df['Away Team Name'] == 'USA')])

21

Now, let's try to find out how many countries participated in the 1986 world cup.

Hint 1: as a first step, create a new data set that only contain games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [5]:
eighty_six = df.loc[df['Year'] == 1986]
e = pd.unique(eighty_six[['Home Team Name', 'Away Team Name']].values.ravel('K'))
len(e)

24

In the world cup history, how matches had more than 5 goals in total?

In [6]:
df['Total Goals'] = df['Home Team Goals'] + df['Away Team Goals']
len(df[df['Total Goals']>=5])

147

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column "Half-time Goals".

In [24]:
df['Half-time Goals'] = df['Half-time Home Goals'] + df['Half-time Away Goals']
df.loc[:,'Year':'Away Team Name'],['Half-time Goals']

(     Year              Datetime                     Stage  \
 0    1930  13 Jul 1930 - 15:00                    Group 1
 1    1930  13 Jul 1930 - 15:00                    Group 4
 2    1930  14 Jul 1930 - 12:45                    Group 2
 3    1930  14 Jul 1930 - 14:50                    Group 3
 4    1930  15 Jul 1930 - 16:00                    Group 1
 5    1930  16 Jul 1930 - 14:45                    Group 1
 6    1930  17 Jul 1930 - 12:45                    Group 2
 7    1930  17 Jul 1930 - 14:45                    Group 4
 8    1930  18 Jul 1930 - 14:30                    Group 3
 9    1930  19 Jul 1930 - 12:50                    Group 1
 10   1930  19 Jul 1930 - 15:00                    Group 1
 11   1930  20 Jul 1930 - 13:00                    Group 2
 12   1930  20 Jul 1930 - 15:00                    Group 4
 13   1930  21 Jul 1930 - 14:50                    Group 3
 14   1930  22 Jul 1930 - 14:45                    Group 1
 15   1930  26 Jul 1930 - 14:45                Semi-finals
 16   1930  27 Jul 1930 - 14:45                Semi-finals
 17   1930  30 Jul 1930 - 14:15                      Final
 18   1934  27 May 1934 - 16:30          Preliminary round
 19   1934  27 May 1934 - 16:30          Preliminary round
 20   1934  27 May 1934 - 16:30          Preliminary round
 21   1934  27 May 1934 - 16:30          Preliminary round
 22   1934  27 May 1934 - 16:30          Preliminary round
 23   1934  27 May 1934 - 16:30          Preliminary round
 24   1934  27 May 1934 - 16:30          Preliminary round
 25   1934  27 May 1934 - 16:30          Preliminary round
 26   1934  31 May 1934 - 16:30             Quarter-finals
 27   1934  31 May 1934 - 16:30             Quarter-finals
 28   1934  31 May 1934 - 16:30             Quarter-finals
 29   1934  31 May 1934 - 16:30             Quarter-finals
 ..    ...                   ...                       ...
 822  2014  30 Jun 2014 - 13:00                Round of 16
 823  2014  30 Jun 2014 - 17:00                Round of 16
 824  2014  04 Jul 2014 - 17:00             Quarter-finals
 825  2014  04 Jul 2014 - 13:00             Quarter-finals
 826  2014  08 Jul 2014 - 17:00                Semi-finals
 827  2014  12 Jul 2014 - 17:00   Play-off for third place
 828  2014  13 Jul 2014 - 16:00                      Final
 829  2014  09 Jul 2014 - 17:00                Semi-finals
 830  2014  05 Jul 2014 - 17:00             Quarter-finals
 831  2014  05 Jul 2014 - 13:00             Quarter-finals
 832  2014  29 Jun 2014 - 13:00                Round of 16
 833  2014  29 Jun 2014 - 17:00                Round of 16
 834  2014  01 Jul 2014 - 13:00                Round of 16
 835  2014  01 Jul 2014 - 17:00                Round of 16
 836  2014  28 Jun 2014 - 13:00                Round of 16
 837  2014  28 Jun 2014 - 17:00                Round of 16
 838  2014  29 Jun 2014 - 13:00                Round of 16
 839  2014  29 Jun 2014 - 17:00                Round of 16
 840  2014  30 Jun 2014 - 13:00                Round of 16
 841  2014  30 Jun 2014 - 17:00                Round of 16
 842  2014  01 Jul 2014 - 13:00                Round of 16
 843  2014  01 Jul 2014 - 17:00                Round of 16
 844  2014  04 Jul 2014 - 13:00             Quarter-finals
 845  2014  04 Jul 2014 - 17:00             Quarter-finals
 846  2014  05 Jul 2014 - 13:00             Quarter-finals
 847  2014  05 Jul 2014 - 17:00             Quarter-finals
 848  2014  08 Jul 2014 - 17:00                Semi-finals
 849  2014  09 Jul 2014 - 17:00                Semi-finals
 850  2014  12 Jul 2014 - 17:00   Play-off for third place
 851  2014  13 Jul 2014 - 16:00                      Final

                      Stadium             City  Home Team Name  \
 0                    Pocitos      Montevideo           France
 1             Parque Central      Montevideo              USA
 2             Parque Central      Montevideo       Yugoslavia
 3                    Pocitos      Montevideo          Romania
 4             Parque Central      Montevideo        Argentina
 5             Parque Central      Montevideo            Chile
 6             Parque Central      Montevideo       Yugoslavia
 7             Parque Central      Montevideo              USA
 8         Estadio Centenario      Montevideo          Uruguay
 9         Estadio Centenario      Montevideo            Chile
 10        Estadio Centenario      Montevideo        Argentina
 11        Estadio Centenario      Montevideo           Brazil
 12        Estadio Centenario      Montevideo         Paraguay
 13        Estadio Centenario      Montevideo          Uruguay
 14        Estadio Centenario      Montevideo        Argentina
 15        Estadio Centenario      Montevideo        Argentina
 16        Estadio Centenario      Montevideo          Uruguay
 17        Estadio Centenario      Montevideo          Uruguay
 18   Stadio Benito Mussolini           Turin          Austria
 19         Giorgio Ascarelli          Naples          Hungary
 20                  San Siro           Milan      Switzerland
 21                 Littorale         Bologna           Sweden
 22            Giovanni Berta        Florence          Germany
 23            Luigi Ferraris           Genoa            Spain
 24             Nazionale PNF            Rome            Italy
 25                  Littorio         Trieste   Czechoslovakia
 26   Stadio Benito Mussolini           Turin   Czechoslovakia
 27                  San Siro           Milan          Germany
 28            Giovanni Berta        Florence            Italy
 29                 Littorale         Bologna          Austria
 ..                       ...              ...             ...
 822         Estadio Nacional        Brasilia           France
 823        Estadio Beira-Rio    Porto Alegre          Germany
 824         Estadio Castelao       Fortaleza           Brazil
 825      Estadio do Maracana  Rio De Janeiro           France
 826         Estadio Mineirao  Belo Horizonte           Brazil
 827         Estadio Nacional        Brasilia           Brazil
 828      Estadio do Maracana  Rio De Janeiro          Germany
 829       Arena de Sao Paulo       Sao Paulo      Netherlands
 830         Arena Fonte Nova        Salvador      Netherlands
 831         Estadio Nacional        Brasilia        Argentina
 832         Estadio Castelao       Fortaleza      Netherlands
 833         Arena Pernambuco          Recife       Costa Rica
 834       Arena de Sao Paulo       Sao Paulo        Argentina
 835         Arena Fonte Nova        Salvador          Belgium
 836         Estadio Mineirao  Belo Horizonte           Brazil
 837      Estadio do Maracana  Rio De Janeiro         Colombia
 838         Estadio Castelao       Fortaleza      Netherlands
 839         Arena Pernambuco          Recife       Costa Rica
 840         Estadio Nacional        Brasilia           France
 841        Estadio Beira-Rio    Porto Alegre          Germany
 842       Arena de Sao Paulo       Sao Paulo        Argentina
 843         Arena Fonte Nova        Salvador          Belgium
 844      Estadio do Maracana  Rio De Janeiro           France
 845         Estadio Castelao       Fortaleza           Brazil
 846         Estadio Nacional        Brasilia        Argentina
 847         Arena Fonte Nova        Salvador      Netherlands
 848         Estadio Mineirao  Belo Horizonte           Brazil
 849       Arena de Sao Paulo       Sao Paulo      Netherlands
 850         Estadio Nacional        Brasilia           Brazil
 851      Estadio do Maracana  Rio De Janeiro          Germany

      Home Team Goals  Away Team Goals Away Team Name
 0                  4                1         Mexico
 1                  3                0        Belgium
 2                  2                1         Brazil
 3                  3                1           Peru
 4                  1                0         France
 5                  3                0         Mexico
 6                  4                0        Bolivia
 7                  3                0       Paraguay
 8                  1                0           Peru
 9                  1                0         France
 10                 6                3         Mexico
 11                 4                0        Bolivia
 12                 1                0        Belgium
 13                 4                0        Romania
 14                 3                1          Chile
 15                 6                1            USA
 16                 6                1     Yugoslavia
 17                 4                2      Argentina
 18                 3                2         France
 19                 4                2          Egypt
 20                 3                2    Netherlands
 21                 3                2      Argentina
 22                 5                2        Belgium
 23                 3                1         Brazil
 24                 7                1            USA
 25                 2                1        Romania
 26                 3                2    Switzerland
 27                 2                1         Sweden
 28                 1                1          Spain
 29                 2                1        Hungary
 ..               ...              ...            ...
 822                2                0        Nigeria
 823                2                1        Algeria
 824                2                1       Colombia
 825                0                1        Germany
 826                1                7        Germany
 827                0                3    Netherlands
 828                1                0      Argentina
 829                0                0      Argentina
 830                0                0     Costa Rica
 831                1                0        Belgium
 832                2                1         Mexico
 833                1                1         Greece
 834                1                0    Switzerland
 835                2                1            USA
 836                1                1          Chile
 837                2                0        Uruguay
 838                2                1         Mexico
 839                1                1         Greece
 840                2                0        Nigeria
 841                2                1        Algeria
 842                1                0    Switzerland
 843                2                1            USA
 844                0                1        Germany
 845                2                1       Colombia
 846                1                0        Belgium
 847                0                0     Costa Rica
 848                1                7        Germany
 849                0                0      Argentina
 850                0                3    Netherlands
 851                1                0      Argentina

 [852 rows x 9 columns], ['Half-time Goals'])

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [25]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ]

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [31]:
df["Home Team Name"].str.contains('Korea'), "Home Team Name"
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name"] = 'Korea'
df.loc[df["Away Team Name"].str.contains('Korea'), "Away Team Name"] = 'Korea'
df.loc[(df['Home Team Initials'] == 'KOR')| df]

Make sure to verify your answer!

In [33]:
df.loc[(df["Home Team Name"] == 'Korea') | (df['Away Team Name'] == 'Korea')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total Goals,Half-time Goals
80,1954,17 Jun 1954 - 18:00,Group 2,Hardturm,Zurich,Hungary,9,0,Korea,,...,0,VINCENTI Raymond (FRA),VON GUNTER Albert (SUI),STEINER Carl (AUT),211,1294,HUN,KOR,9,4
88,1954,20 Jun 1954 - 17:00,Group 2,Charmilles,Geneva,Turkey,7,0,Korea,,...,0,MARINO Esteban (URU),ORLANDINI Vincenzo (ITA),SCHONHOLZER Ernest (SUI),211,1304,TUR,KOR,7,4
171,1966,12 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Soviet Union,3,0,Korea,,...,0,GARDEAZABAL Juan (ESP),KANDIL Aly Hussein (EGY),DIENST Gottfried (SUI),238,1710,URS,PRK,3,2
179,1966,15 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,1,Chile,,...,1,KANDIL Aly Hussein (EGY),CRAWFORD William (SCO),FINNEY Jim (ENG),238,1609,PRK,CHI,2,1
187,1966,19 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,0,Italy,,...,0,SCHWINTE Pierre (FRA),ADAIR John (NIR),TAYLOR John (ENG),238,1679,PRK,ITA,1,1
195,1966,23 Jul 1966 - 15:00,Quarter-finals,Goodison Park,Liverpool,Portugal,5,3,Korea,,...,3,ASHKENAZI Menachem (ISR),GALBA Karol (TCH),SCHWINTE Pierre (FRA),239,1702,POR,PRK,8,5
364,1986,02 Jun 1986 - 12:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Argentina,3,1,Korea,,...,0,SANCHEZ ARMINIO Victoriano (ESP),GONZALEZ ROA Gabriel (PAR),DIAZ PALACIO Jesus (COL),308,395,ARG,KOR,4,2
374,1986,05 Jun 1986 - 16:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Korea,1,1,Bulgaria,,...,1,AL SHANAR Fallaj Khuzam (KSA),IGNA Ioan (ROU),BUTENKO Valeri (RUS),308,460,KOR,BUL,2,1
386,1986,10 Jun 1986 - 12:00,Group A,Cuauhtemoc,Puebla,Korea,2,3,Italy,,...,1,SOCHA David (USA),URREA Joaquin (MEX),AL SHARIF Jamal (SYR),308,643,KOR,ITA,5,1
421,1990,12 Jun 1990 - 17:00,Group E,Marc Antonio Bentegodi,Verona,Belgium,2,0,Korea,,...,0,MAURO Vincent (USA),SNODDY Alan (NIR),COURTNEY George (ENG),322,57,BEL,KOR,2,0
434,1990,17 Jun 1990 - 21:00,Group E,Dacia Arena,Udine,Korea,1,3,Spain,,...,1,JACOME GUERRERO Elias V. (ECU),MAGNI Pierluigi (ITA),LOUSTAU Juan (ARG),322,175,KOR,ESP,4,2
444,1990,21 Jun 1990 - 17:00,Group E,Friuli,Udine,Korea,0,1,Uruguay,,...,0,LANESE Tullio (ITA),DIRAMBA Jean Fidele (GAB),JOUINI Neji (TUN),322,290,KOR,URU,1,0
464,1994,17 Jun 1994 - 19:30,Group C,Cotton Bowl,Dallas,Spain,2,2,Korea,,...,0,MIKKELSEN Peter (DEN),CHRISTENSEN Carl-Johan Meyer (DEN),PEARSON Roy (ENG),337,3050,ESP,KOR,4,0
480,1994,23 Jun 1994 - 19:30,Group C,Foxboro Stadium,Boston,Korea,0,0,Bolivia,,...,0,MOTTRAM Leslie (SCO),MATTHYS Luc (BEL),EVERSTIG Mikael (SWE),337,3065,KOR,BOL,0,0
490,1994,27 Jun 1994 - 16:00,Group C,Cotton Bowl,Dallas,Germany,3,2,Korea,,...,0,QUINIOU Joel (FRA),IVANOV Valentin (RUS),HASSAN Abdel-Magid (EGY),337,3076,GER,KOR,5,3
524,1998,13 Jun 1998 - 17:30,Group E,Stade de Gerland,Lyon,Korea,1,3,Mexico,,...,0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014,8732,KOR,MEX,4,1
542,1998,20 Jun 1998 - 21:00,Group E,Stade V�lodrome,Marseilles,Netherlands,5,0,Korea,,...,0,WOJCIK Ryszard (POL),POCIEGIEL Jacek (POL),DUPANOV Yuri (BLR),1014,8749,NED,KOR,5,2
556,1998,25 Jun 1998 - 16:00,Group E,Parc des Princes,Paris,Belgium,1,1,Korea,,...,0,REZENDE Marcio (BRA),PINTO Arnaldo (BRA),ARANGO Jorge Luis (COL),1014,8765,BEL,KOR,2,1
593,2002,04 Jun 2002 - 20:30,Group D,Busan Asiad Main Stadium,Busan,Korea,2,0,Poland,,...,0,RUIZ Oscar (COL),DORIRI Elise (VAN),LINDBERG Leif (SWE),43950100,43950014,KOR,POL,2,1
609,2002,10 Jun 2002 - 15:30,Group D,Daegu World Cup Stadium,Daegu,Korea,1,1,USA,,...,1,MEIER Urs (SUI),BEREUTER Egon (AUT),TOMUSANGE Ali (UGA),43950100,43950030,KOR,USA,2,1
625,2002,14 Jun 2002 - 20:30,Group D,Incheon Football Stadium,Incheon,Portugal,0,1,Korea,,...,0,SANCHEZ Angel (ARG),ALTRAIFI Ali (KSA),SZEKELY Ferenc (HUN),43950100,43950047,POR,KOR,1,0
635,2002,18 Jun 2002 - 20:30,Round of 16,Daejeon World Cup Stadium,Daejeon,Korea,2,1,Italy,Win on Golden Goal,...,0,MORENO Byron (ECU),RATTALINO Jorge (ARG),SZEKELY Ferenc (HUN),43950200,43950056,KOR,ITA,3,0
639,2002,22 Jun 2002 - 15:30,Quarter-finals,Gwangju World Cup Stadium,Gwangju,Spain,0,0,Korea,Korea Republic win on penalties (3 - 5),...,0,EL GHANDOUR Gamal (EGY),TOMUSANGE Ali (UGA),RAGOONATH Michael (TRI),43950300,43950059,ESP,KOR,0,0
640,2002,25 Jun 2002 - 20:30,Semi-finals,Seoul World Cup Stadium,Seoul,Germany,1,0,Korea,,...,0,MEIER Urs (SUI),ARNAULT Frederic (FRA),AMLER Evzen (CZE),43950400,43950061,GER,KOR,1,0
642,2002,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea,2,3,Turkey,,...,3,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500,43950063,KOR,TUR,5,4
655,2006,13 Jun 2006 - 15:00,Group G,"FIFA World Cup Stadium, Frankfurt",Frankfurt/Main,Korea,2,1,Togo,,...,1,POLL Graham (ENG),SHARP Philip (ENG),TURNER Glenn (ENG),97410100,97410014,KOR,TOG,3,1
672,2006,18 Jun 2006 - 21:00,Group G,Zentralstadion,Leipzig,France,1,1,Korea,,...,0,ARCHUNDIA Benito (MEX),RAMIREZ Jose (MEX),VERGARA Hector (CAN),97410100,97410029,FRA,KOR,2,1
691,2006,23 Jun 2006 - 21:00,Group G,"FIFA World Cup Stadium, Hanover",Hanover,Switzerland,2,0,Korea,,...,0,ELIZONDO Horacio (ARG),GARCIA Dario (ARG),OTERO Rodolfo (ARG),97410100,97410046,SUI,KOR,2,1
710,2010,12 Jun 2010 - 13:30,Group B,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea,2,0,Greece,,...,0,HESTER Michael (NZL),HINTZ Jan Hendrik (NZL),MAKASINI Tevita (TGA),249722,300061459,KOR,GRE,2,1
721,2010,15 Jun 2010 - 20:30,Group G,Ellis Park Stadium,Johannesburg,Brazil,2,1,Korea,,...,0,KASSAI Viktor (HUN),EROS Gabor (HUN),VAMOS Tibor (HUN),249722,300061490,BRA,PRK,3,0
725,2010,17 Jun 2010 - 13:30,Group B,Soccer City Stadium,Johannesburg,Argentina,4,1,Korea,,...,1,DE BLEECKERE Frank (BEL),HERMANS Peter (BEL),VROMANS Walter (BEL),249722,300061458,ARG,KOR,5,3
737,2010,21 Jun 2010 - 13:30,Group G,Cape Town Stadium,Cape Town,Portugal,7,0,Korea,,...,0,POZO Pablo (CHI),BASUALTO Patricio (CHI),MONDRIA Francisco (CHI),249722,300061487,POR,PRK,7,1
742,2010,22 Jun 2010 - 20:30,Group B,Durban Stadium,Durban,Nigeria,2,2,Korea,,...,1,Oleg�rio BENQUEREN�A (POR),CARDINAL Jose (POR),MIRANDA Bertino (POR),249722,300111115,NGA,KOR,4,2
753,2010,25 Jun 2010 - 16:00,Group G,Mbombela Stadium,Nelspruit,Korea,0,3,C�te d'Ivoire,,...,2,Alberto UNDIANO MALLENCO (ESP),MARTINEZ Fermin (ESP),YUSTE Juan (ESP),249722,300061486,PRK,CIV,3,2
756,2010,26 Jun 2010 - 16:00,Round of 16,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Uruguay,2,1,Korea,,...,0,Wolfgang STARK (GER),SALVER Jan-Hendrik (GER),PICKEL Mike (GER),249717,300061504,URU,KOR,3,1
788,2014,17 Jun 2014 - 18:00,Group H,Arena Pantanal,Cuiaba,Russia,1,1,Korea,,...,0,PITANA Nestor (ARG),MAIDANA Hernan (ARG),BELATTI Juan Pablo (ARG),255931,300186499,RUS,KOR,2,0
802,2014,22 Jun 2014 - 16:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea,2,4,Algeria,,...,3,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931,300186495,KOR,ALG,6,3
818,2014,26 Jun 2014 - 17:00,Group H,Arena de Sao Paulo,Sao Paulo,Korea,0,1,Belgium,,...,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255931,300186480,KOR,BEL,1,0